version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_IMAGE:-panchesco13/banknote-classifier}:${TAG:-latest}
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"