name: Continuous Deployment

on:
  repository_dispatch:
    types:
      - cd-trigger

env:
  DOCKER_IMAGE: panchesco13/banknote-classifier

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          docker build -t test-image .
          docker run --rm test-image pytest

      - name: Run functional tests
        run: |
          docker run -d -p 8080:8080 ${{ env.DOCKER_IMAGE }}:sha-${{ github.sha }}
          echo "Waiting for server to start..."
          sleep 15

          echo "Checking health endpoint..."
          curl -f http://localhost:8080/health

          echo "Running functional tests..."
          python tests/test_functional.py