name: Docker Build and Publish

on:
  pull_request:
    branches: [ main, master ]

env:
  DOCKER_IMAGE: panchesco13/banknote-classifier

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Verify Docker login
      run: |
        docker info
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Generate tag
      id: tag
      run: |
        SHA_SHORT=$(echo ${{ github.sha }} | cut -c1-7)
        echo "TAG=${SHA_SHORT}" >> $GITHUB_ENV
        echo "tag=${SHA_SHORT}" >> $GITHUB_OUTPUT

    - name: Build with docker compose
      run: |
        docker compose build

    - name: Tag the image
      run: |
        docker tag ${DOCKER_IMAGE}:latest ${DOCKER_IMAGE}:${{ github.ref_name }}

    - name: Push to DockerHub
      run: |
        docker push ${DOCKER_IMAGE}:${{ github.ref_name }}

    - name: Trigger CD workflow
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/dispatches \
          -d '{"event_type":"cd-trigger"}'